apiVersion: v2
name: dagster-authkit
description: Community authentication wrapper for self-hosted Dagster OSS
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - dagster
  - authentication
  - rbac
  - security
  - self-hosted
maintainers:
  - name: Demetrius Albuquerque
    email: demetrius.albuquerque@yahoo.com.br
icon: https://raw.githubusercontent.com/maltzsama/dagster-authkit/main/docs/assets/icon.png
